### ISSUE TITLE
Some polymer update broke the element

### ISSUE THREAD

**Issue by vinerz** [The5heepDev/iron-grid#10]
Hello! Some Polymer recent update broke the element. The column gets the right size, but they get all wrapped.
Even the demo is broken right now, as the screenshot shows:

![image](https://cloud.githubusercontent.com/assets/1482034/12430309/262d74d4-bed6-11e5-9465-0e700bb9eaf5.png)

**Comment by ozwaldorf** [comment]
Is this with polymer 1.2.0?

**Comment by vinerz** [comment]
I am using the newest version, 1.2.3

**Comment by ozwaldorf** [comment]
I have switched the px10 resizer to the original, which has 1.2.0 compatibility.

**Comment by vinerz** [comment]
Awesome! Thank you very much.
But the bower.json got broken, it is missing a quote there

**Comment by ozwaldorf** [comment]
Fixed!

**Comment by vinerz** [comment]
Thank you, I think we're almost there. I got this error issuing a `bower update`

![image](https://cloud.githubusercontent.com/assets/1482034/12430964/e2b5d0e4-bed9-11e5-9fb2-8ced1a237912.png)

**Comment by ozwaldorf** [comment]
It looks like the latest px10 version isn't on bower. I'll try switching over to iron-resizable-behavior.

**Comment by ozwaldorf** [comment]
Try it now.

**Comment by vinerz** [comment]
Hi, sorry for the delay. There are some methods mistyping I guess. Also, the path to iron-resizable-behavior seems to be incorrect, it should be `../iron-resizable-behavior/iron-resizable-behavior.html`

![image](https://cloud.githubusercontent.com/assets/1482034/12432057/199fa9ee-bee0-11e5-95c6-1ef35a632e38.png)

**Comment by ozwaldorf** [comment]
Ok, everything lines up now.

**Comment by vinerz** [comment]
Those errors went away, but the alignment is still broken. :(
I am even using the demo.html too to isolate it from my app styling and it is also broken.

**Comment by ozwaldorf** [comment]
Try now

**Comment by vinerz** [comment]
Just tried a clean install, no luck.

**Comment by faridelnasire** [comment]
Just installed/used it for the first time about 30 minutes ago, having the same issue. Using Polymer 1.2.0.

<img width="930" alt="screen shot 2016-01-20 at 1 01 28 am" src="https://cloud.githubusercontent.com/assets/8388199/12441088/7eaf5060-bf11-11e5-8507-1470e10de686.png">

<img width="517" alt="screen shot 2016-01-20 at 1 04 18 am" src="https://cloud.githubusercontent.com/assets/8388199/12441113/caf02990-bf11-11e5-8696-ed8b1c327be2.png">

**Comment by vinerz** [comment]
@faridelnasire, I am currently working on a temporary fix for this. I might make a pull request in five minutes.

**Comment by vinerz** [comment]
@faridelnasire, please check https://github.com/The5heepDev/iron-grid/pull/11

**Comment by ozwaldorf** [comment]
Thank you @vinerz !

**Comment by vinerz** [comment]
You are very welcome, @The5heepDev :)

**Comment by maxiplay** [comment]
I did not use the iron-resizable-behavior.html because it does not work well with nested element.

**Comment by faridelnasire** [comment]
That fixed it for me, you both rule! :+1:  @vinerz @The5heepDev
