### ISSUE TITLE
Hidding elements does not work

### ISSUE THREAD

**Issue by TomasAgoston** [The5heepDev/iron-grid#12]
Hidding an element for a screen format does not work with the current version 3.0.0.

F.e. in the demo change 

```
...
            <div class="s12 example blue">
                <p>s12</p>
            </div>
....
```

to

```
...
            <div class="s0 m12 example blue">
                <p>s12</p>
            </div>
...
```

The blue element is always hidden, also for medium size and larger.

**Comment by TomasAgoston** [comment]
Any update on the element hidding issue?

**Comment by ozwaldorf** [comment]
Sorry, no. I will look into this soon, though.

**Comment by maxiplay** [comment]
There is now a pull request for this problem.

**Comment by TomasAgoston** [comment]
Hi,

thanks for the update. But it is still not working as expected. See the current 3.1.1 demo version:

```
            <div class="xl0 s12 example blue">
                <p>s12</p>
            </div>
```

I would expect to see the blue element visible for the xl size, but the element is always hidden.

**Comment by maxiplay** [comment]
Indeed, I did not manage this use case. There is now a new pull request for it.

**Comment by maxiplay** [comment]
https://github.com/The5heepDev/iron-grid/pull/18

**Comment by ozwaldorf** [comment]
@maxiplay Merged. Thanks!
