### ISSUE TITLE
Polymer & Webcomponents conflict

### ISSUE THREAD

**Issue by gulyasfeccferenc** [The5heepDev/iron-grid#2]
When imported in project where already included polymer and my own webcomponents dependencies its totally break everything. After remove the first two (import) line from iron-grid.html its working like charm, but its too difficult remove these lines at every build. Do you have any idea how to solve this?

**Comment by ozwaldorf** [comment]
Could you email me your current code? Are you using the latest version of polymer? I cant think of anything without seeing your code.

**Comment by ozwaldorf** [comment]
My email is the5heepdev@gmail.com

**Comment by ozwaldorf** [comment]
Should be fixed now, please re-download and try again!
