### ISSUE TITLE
Is not Compatible with Polymer2.0

### ISSUE THREAD

**Issue by Borjagodoy** [The5heepDev/iron-grid#35]
Hi!! I need use your component with polymer 2. I can do a PR with the changes in the code (content = slot) for the compatiblity of the component.

Is a interesting PR by the road map of the component?

**Comment by ozwaldorf** [comment]
If you have a fork with a fix for polymer 2.0, go ahead and make a PR!

**Comment by maxiplay** [comment]
I tried to create a Polymer 2 version but the shadow dom v1 spec has limitations 
First is https://github.com/webcomponents/shadycss/issues/5

Second is
Selects distributed nodes inside of an element. ::content was renamed to ::slotted but as of yet no browser has shipped the renamed version. It's important to note that ::slotted can only select top-level children, **it can't do descendant selectors.**

/* Current implementation in Chrome */
::content h1 {
  color: red;
}

/* Upcoming implementation in Chrome and Safari */
::slotted(h1) {
  color: red;
}

**Comment by maxiplay** [comment]
Will need to apply css dynamically but with a certain cost

**Comment by DarkSideOfMo0n** [comment]
I just created a PR for Polymer 2 compatibility. Please review!
https://github.com/The5heepDev/iron-grid/pull/40

**Comment by onlinerahul** [comment]
So now is the grid system compatible with polymer 2? Can we use now? also is this grid support IE ?
