### ISSUE TITLE
Hiding a column

### ISSUE THREAD

**Issue by niknetniko** [The5heepDev/iron-grid#4]
Would it be possible to implement something to hide columns?

I was thinking about maybe the classes `s0 m0 l0`?

That way I could hide certain columns on mobile:

``` html
<!-- Will not be shown on mobile -->
<div class="s0 m6">
Only for medium and large devices!
</div>
```

Thank you for this awesome element!

**Comment by ozwaldorf** [comment]
Yes! Great idea! Sorry for the late reply -- I have been very busy lately. 

I will work on this soon!

**Comment by ozwaldorf** [comment]
Done! Just update and use the magic!

**Comment by theRod15** [comment]
Love this!
