### ISSUE TITLE
Responsive layout does not work

### ISSUE THREAD

**Issue by TomasAgoston** [The5heepDev/iron-grid#9]
Hi there,

upgraded to the latest version from 1.4.2. It doesn't seem to work for us. The layouting is not happening during browser resize (which it did before). The Demo is also not working, maybe let us start there.

**Comment by ozwaldorf** [comment]
Do you have version 2.0.0?

**Comment by TomasAgoston** [comment]
It was 2.0.0. Currently having lastest version 2.2.2 with Polymer 1.2.3. Still not working. Same issue as #10.

**Comment by ozwaldorf** [comment]
The latest version is fixed!

**Comment by TomasAgoston** [comment]
Good job!
